// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using videojuegosev.Models;

#nullable disable

namespace videojuegosev.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251026192831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("videojuegosev.Models.Desarrolladora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AñoFundacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Desarrolladoras");
                });

            modelBuilder.Entity("videojuegosev.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("videojuegosev.Models.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AñoLanzamiento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plataformas");
                });

            modelBuilder.Entity("videojuegosev.Models.Videojuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DesarrolladoraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DesarrolladoraId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Videojuegos");
                });

            modelBuilder.Entity("videojuegosev.Models.VideojuegoPlataforma", b =>
                {
                    b.Property<int>("VideojuegoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VideojuegoId", "PlataformaId");

                    b.HasIndex("PlataformaId");

                    b.ToTable("VideojuegoPlataformas");
                });

            modelBuilder.Entity("videojuegosev.Models.Videojuego", b =>
                {
                    b.HasOne("videojuegosev.Models.Desarrolladora", "Desarrolladora")
                        .WithMany("Videojuegos")
                        .HasForeignKey("DesarrolladoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("videojuegosev.Models.Genero", "Genero")
                        .WithMany("Videojuegos")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desarrolladora");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("videojuegosev.Models.VideojuegoPlataforma", b =>
                {
                    b.HasOne("videojuegosev.Models.Plataforma", "Plataforma")
                        .WithMany("VideojuegoPlataformas")
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("videojuegosev.Models.Videojuego", "Videojuego")
                        .WithMany("VideojuegoPlataformas")
                        .HasForeignKey("VideojuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plataforma");

                    b.Navigation("Videojuego");
                });

            modelBuilder.Entity("videojuegosev.Models.Desarrolladora", b =>
                {
                    b.Navigation("Videojuegos");
                });

            modelBuilder.Entity("videojuegosev.Models.Genero", b =>
                {
                    b.Navigation("Videojuegos");
                });

            modelBuilder.Entity("videojuegosev.Models.Plataforma", b =>
                {
                    b.Navigation("VideojuegoPlataformas");
                });

            modelBuilder.Entity("videojuegosev.Models.Videojuego", b =>
                {
                    b.Navigation("VideojuegoPlataformas");
                });
#pragma warning restore 612, 618
        }
    }
}
